In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = [[1, 20, '2019-08-14'], [2, 50, '2019-08-14'], [1, 30, '2019-08-15'], [1, 35, '2019-08-16'], [2, 65, '2019-08-17'], [3, 20, '2019-08-18']]
products = pd.DataFrame(data, columns=['product_id', 'new_price', 'change_date']).astype({'product_id':'Int64', 'new_price':'Int64', 'change_date':'datetime64[ns]'})

In [6]:
products

   product_id  new_price change_date
0           1         20  2019-08-14
1           2         50  2019-08-14
2           1         30  2019-08-15
3           1         35  2019-08-16
4           2         65  2019-08-17
5           3         20  2019-08-18

In [78]:
latest=products[products["change_date"]<="2019-08-16"].sort_values("change_date").groupby("product_id").last().reset_index()[["product_id","new_price"]].rename(columns={"new_price":"price"})

In [79]:
latest

   product_id  price
0           1     35
1           2     50

In [70]:
all_products=products[["product_id"]].drop_duplicates()

In [71]:
all_products

   product_id
0           1
1           2
5           3

In [73]:
missing = all_products[~all_products['product_id'].isin(latest['product_id'])]
missing['price'] = 10

C:\Users\Nadeem Anwar\AppData\Local\Temp\ipykernel_8496\2688834401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing['price'] = 10

missing=all_products[~all_products.isin(latest["product_id"])]
missing["price"]=10

In [74]:
missing

   product_id  price
5           3     10

In [75]:
pd.concat([latest,missing],ignore_index=True)

   product_id  price
0           1     35
1           2     50
2           3     10

In [ ]:
df_filtered = df[df['change_date'] <= '2019-08-16']

latest = (
    df_filtered
    .sort_values('change_date')
    .groupby('product_id')
    .last()
    .reset_index()[['product_id', 'new_price']]
    .rename(columns={'new_price': 'price'})
)

all_products = df[['product_id']].drop_duplicates()

missing = all_products[~all_products['product_id'].isin(latest['product_id'])]
missing['price'] = 10

result = pd.concat([latest, missing], ignore_index=True)